
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvxlgmkcmdtkceabvqic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2eGxnbWtjbWR0a2NlYWJ2cWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTc2NTgsImV4cCI6MjA2MjEzMzY1OH0.7LLeoApApavYP2ahh6pVmGLRmfWdl4FcUvG84s4pJ98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true, 
    storage: localStorage
  }
});
